#! bin/php
<?php

use \FOXALLIES\Framework;

require __DIR__ . '/vendor/autoload.php';
global $framework;
$framework = new Framework();
$framework->database();
$classes = [];
foreach (glob('./database/tables/*.php') as $file) {
    include $file;
    $classes[] = [
        'path' => $file,
        'class_name' => get_declared_classes()[array_key_last(get_declared_classes())]
    ];
}

function resetDatabase($classes)
{
    global $framework;
    $framework->database->getConnection()->getSchemaBuilder()->disableForeignKeyConstraints();
    foreach ($classes as $item) {
        try {
            $ref = new \ReflectionClass($item['class_name']);
            $migration = $ref->newInstance();
            $migration->down();
        } catch (\ReflectionException $e) {
            var_dump($e);
        }
    }
    $framework->database->getConnection()->getSchemaBuilder()->enableForeignKeyConstraints();
}

function buildDatabase($classes)
{
    foreach ($classes as $item) {
        try {
            $ref = new \ReflectionClass($item['class_name']);
            $migration = $ref->newInstance();
            $migration->boot();
        } catch (\ReflectionException $e) {
            var_dump($e);
        }
    }
}

function seedDatabase()
{
    global $framework;
    include "./database/seeds/DatabaseSeeder.php";
    (new DatabaseSeeder())->boot($framework->database->getConnection()->getSchemaBuilder());
}

resetDatabase($classes);
buildDatabase($classes);
seedDatabase();
